### ISSUE TITLE
conflicts with a previous declaration

### ISSUE THREAD

**Issue by AnthonyM17** [xylar/acciv#7]
Hi All,
I am experiencing a problem with a variable deceleration.  Here is the full error:
ACCIVPass.cpp: In function ‘SInt32 lround(float)’:
ACCIVPass.cpp:22:22: error: ‘SInt32 lround(float)’ conflicts with a previous declaration
 SInt32 lround(float x)
                      ^
In file included from /usr/include/c++/6/math.h:36:0,
                 from vector2.h:18,
                 from VectorField2D.h:8,
                 from ACCIVPass.h:6,
                 from ACCIVPass.cpp:1:
/usr/include/c++/6/cmath:1658:3: note: previous declaration ‘constexpr long int std::lround(float)’
   lround(float __x)
   ^~~~~~
Makefile:39: recipe for target 'ACCIVPass.o' failed
make: *** [ACCIVPass.o] Error 1

I was using the Makefile with g++ but I also tried cc.  Both compilers gave me this error.
Would you have any suggestions?

Thank you,
Anthony

**Comment by xylar** [comment]
@AnthonyM17, thank you for bringing this issue to my attention.  I can reproduce the error and should be able to post a fix very soon.

**Comment by AnthonyM17** [comment]
Hi I believe you have fixed the problem.  
I can compile the code with no errors.  
I was getting this additional error (shown below), but i was using "cc" as my compiler instead of g++ as was the default.
Thank You, no compiler errors to report as of now.
/usr/bin/ld: /usr/local/lib/libfftw3.a(mapflags.o): undefined reference to symbol '__log_finite@@GLIBC_2.15'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'acciv_main' failed
make: *** [acciv_main] Error 1

**Comment by xylar** [comment]
Hi @AnthonyM17, I tested with g++.  I don't think I currently have any other compilers installed but if you would rather be using cc, let me know and I can try to debug this other issue.  It would certainly be nice to have it working with other compilers.

Let me know as well if you run into other trouble.

**Comment by AnthonyM17** [comment]
Hi, No g++ is fine.  Thank You!
